# Generated by Django 3.0.6 on 2020-05-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amberapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
