# Generated by Django 3.0.6 on 2020-05-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Provide name of your service', max_length=50)),
                ('description', models.CharField(help_text='Provide short decription', max_length=500)),
                ('bootstrap_icon', models.CharField(help_text='Enter bootstrap icon here', max_length=500)),
                ('link', models.CharField(help_text='Provide link to an action', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter task title', max_length=50)),
                ('description', models.CharField(help_text='Enter task description', max_length=500)),
                ('bootstrap_icon', models.CharField(help_text='Enter bootstrap icon here', max_length=500)),
                ('link', models.CharField(help_text='Путь к настройке задания', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViberToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telegram_tokens', models.ManyToManyField(to='botapp.TelegramToken')),
                ('viber_tokens', models.ManyToManyField(to='botapp.ViberToken')),
            ],
        ),
    ]
