# Generated by Django 3.0.7 on 2020-07-08 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isJoint',
            field=models.BooleanField(default=False, verbose_name='Совместные покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='joined',
            field=models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
