# Generated by Django 3.0.7 on 2020-07-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200708_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isJoint',
        ),
        migrations.RemoveField(
            model_name='product',
            name='joined',
        ),
        migrations.CreateModel(
            name='JointProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('joined', models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('products.product',),
        ),
    ]
